@extends('layouts.admin')
@section('title', 'Penyewa')
@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-3xl font-extrabold sm:text-4xl">Data Penyewa Aktif</h1><p class="mt-2 text-sm text-slate-500">Manage and monitor all currently active tenants across properties.</p></div><a href="{{ route('tenants.create') }}" class="btn-primary w-full sm:w-auto"><x-icon name="plus"/> Tambah Penyewa</a></div>
<form class="panel mb-8 grid gap-4 p-4 sm:p-6 md:grid-cols-2 xl:grid-cols-[1fr_180px_180px_auto]"><div class="relative md:col-span-2 xl:col-span-1"><x-icon name="search" class="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input name="search" value="{{ request('search') }}" class="form-input pl-12" placeholder="Cari nama penyewa..."></div><select name="kost_id" class="form-select"><option value="">Semua Kost</option>@foreach($kosts as $kost)<option value="{{ $kost->id }}" @selected(request('kost_id') == $kost->id)>{{ $kost->name }}</option>@endforeach</select><select name="status" class="form-select"><option value="">Semua Status</option><option value="active" @selected(request('status', 'active') === 'active')>Status: Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Tidak Aktif</option></select><button class="btn-secondary md:col-span-2 xl:col-span-1"><x-icon name="filter"/> Terapkan</button></form>
<section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[1000px]"><thead><tr><th class="table-heading">Nama Penyewa</th><th class="table-heading">Nomor HP</th><th class="table-heading">Kost</th><th class="table-heading">Kamar</th><th class="table-heading">Tanggal Masuk</th><th class="table-heading">Status</th><th class="table-heading text-right">Aksi</th></tr></thead><tbody>
@forelse($tenants as $tenant)<tr><td class="table-cell"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-blue-100 text-xs font-bold text-[#12347f]">{{ Str::upper(Str::substr($tenant->user->name, 0, 2)) }}</span><div><p class="font-semibold text-slate-900">{{ $tenant->user->name }}</p><p class="text-[11px] {{ $tenant->identity_verification_status->value === 'verified' ? 'text-slate-500' : 'text-red-500' }}">KTP {{ ucfirst($tenant->identity_verification_status->value) }}</p></div></div></td><td class="table-cell">{{ $tenant->user->phone ?: '-' }}</td><td class="table-cell">{{ $tenant->room->kost->name }}</td><td class="table-cell">{{ $tenant->room->room_number }}</td><td class="table-cell">{{ $tenant->check_in->format('d M Y') }}</td><td class="table-cell"><span class="rounded-full bg-emerald-300 px-3 py-1 text-xs font-semibold text-emerald-800">{{ $tenant->status->value === 'active' ? 'Aktif' : 'Nonaktif' }}</span></td><td class="table-cell"><div class="flex justify-end gap-1"><a href="{{ route('tenants.show', $tenant) }}" class="rounded p-2 text-slate-500 hover:bg-blue-50"><x-icon name="eye"/></a><a href="{{ route('tenants.edit', $tenant) }}" class="rounded p-2 text-slate-500 hover:bg-blue-50"><x-icon name="edit"/></a><form method="POST" action="{{ route('tenants.destroy', $tenant) }}" data-confirm="Hapus data penyewa ini?">@csrf @method('DELETE')<button class="rounded p-2 text-red-500 hover:bg-red-50"><x-icon name="trash"/></button></form></div></td></tr>
@empty<tr><td colspan="7" class="py-16 text-center text-sm text-slate-500">Tidak ada data penyewa.</td></tr>@endforelse
</tbody></table></div><div class="p-6">{{ $tenants->links() }}</div></section>
@endsection
