@extends('layouts.admin')
@section('title', 'Pembayaran')
@section('content')
<div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-2xl font-extrabold sm:text-3xl">Verifikasi Pembayaran</h1><p class="mt-2 text-sm text-slate-500">Review and manage pending tenant payments.</p></div><form class="w-full sm:w-auto"><select name="status" class="form-select w-full sm:w-44" onchange="this.form.submit()"><option value="pending" @selected(request('status', 'pending') === 'pending')>Menunggu</option><option value="approved" @selected(request('status') === 'approved')>Approved</option><option value="rejected" @selected(request('status') === 'rejected')>Rejected</option></select></form></div>
<div class="grid gap-6 xl:grid-cols-[1fr_330px]"><section class="panel overflow-hidden"><div class="flex items-center justify-between border-b border-slate-200 px-6 py-6"><h2 class="text-lg font-extrabold">Pending Verification</h2><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-[#12347f]">{{ $payments->total() }} Data</span></div><div class="overflow-x-auto"><table class="w-full min-w-[650px]"><thead><tr><th class="table-heading">ID Transaksi</th><th class="table-heading">Nama Penyewa</th><th class="table-heading">Jumlah</th><th class="table-heading">Bukti</th><th class="table-heading">Status</th></tr></thead><tbody>
@forelse($payments as $payment)<tr class="{{ $selectedPayment?->is($payment) ? 'bg-[#edf2ff]' : 'hover:bg-slate-50' }}"><td class="table-cell"><a class="font-bold text-slate-900" href="{{ route('payments.index', ['status' => request('status', 'pending'), 'payment' => $payment]) }}">#{{ $payment->transaction_code }}</a></td><td class="table-cell"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-[#244393] text-xs text-white">{{ Str::upper(Str::substr($payment->booking->user->name,0,2)) }}</span><div><p class="font-semibold text-slate-900">{{ $payment->booking->user->name }}</p><p class="text-xs">Kamar {{ $payment->booking->room->room_number }}</p></div></div></td><td class="table-cell">Rp<br>{{ number_format($payment->amount, 0, ',', '.') }}</td><td class="table-cell"><span class="grid h-12 w-12 place-items-center overflow-hidden rounded border border-slate-300 bg-blue-50">@if($payment->proof_image && Storage::disk('public')->exists($payment->proof_image))<img src="{{ Storage::url($payment->proof_image) }}" class="h-full w-full object-cover">@else<x-icon name="payment" class="h-5 w-5 text-slate-500"/>@endif</span></td><td class="table-cell"><span @class(['rounded-full px-3 py-2 text-[11px] font-semibold', 'bg-blue-100 text-[#12347f]' => $payment->status->value === 'pending', 'bg-emerald-100 text-emerald-700' => $payment->status->value === 'approved', 'bg-red-100 text-red-700' => $payment->status->value === 'rejected'])>● {{ $payment->status->value === 'pending' ? 'Menunggu Verifikasi' : ucfirst($payment->status->value) }}</span></td></tr>
@empty<tr><td colspan="5" class="py-20 text-center text-sm text-slate-500">Tidak ada pembayaran pada status ini.</td></tr>@endforelse
</tbody></table></div><div class="p-5">{{ $payments->links() }}</div></section>

<aside class="panel flex min-h-[650px] flex-col overflow-hidden"><div class="border-b border-slate-200 px-6 py-6"><h2 class="text-lg font-extrabold">Preview Bukti Transfer</h2></div>@if($selectedPayment)<div class="flex-1 p-6"><div class="grid h-72 place-items-center overflow-hidden rounded-lg border border-slate-300 bg-[#eaf0ff]">@if($selectedPayment->proof_image && Storage::disk('public')->exists($selectedPayment->proof_image))<img src="{{ Storage::url($selectedPayment->proof_image) }}" class="h-full w-full object-contain">@else<div class="text-center text-slate-400"><x-icon name="payment" class="mx-auto h-14 w-14"/><p class="mt-3 text-xs">Bukti transfer</p></div>@endif</div><div class="mt-6 rounded-lg border border-slate-300 p-5"><h3 class="text-xs font-bold tracking-wide text-slate-500">TRANSACTION DETAILS</h3><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500">ID</dt><dd class="font-semibold">#{{ $selectedPayment->transaction_code }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Penyewa</dt><dd class="font-semibold text-right">{{ $selectedPayment->booking->user->name }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Kamar</dt><dd class="font-semibold">{{ $selectedPayment->booking->room->room_number }}</dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Tanggal</dt><dd class="text-right font-semibold">{{ optional($selectedPayment->submitted_at)->format('d M Y, H:i') }}</dd></div><div class="flex items-end justify-between border-t border-slate-300 pt-4"><dt class="text-slate-500">Jumlah</dt><dd class="text-right text-xl font-extrabold text-[#12347f]">Rp<br>{{ number_format($selectedPayment->amount, 0, ',', '.') }}</dd></div></dl></div></div>@if($selectedPayment->status->value === 'pending')<div class="grid grid-cols-2 gap-4 border-t border-slate-200 p-6"><form method="POST" action="{{ route('payments.reject', $selectedPayment) }}">@csrf @method('PATCH')<button class="btn-secondary w-full !border-red-400 !text-red-600"><x-icon name="x"/> Reject</button></form><form method="POST" action="{{ route('payments.approve', $selectedPayment) }}">@csrf @method('PATCH')<button class="btn-primary w-full"><x-icon name="check"/> Approve</button></form></div>@endif @else<div class="grid flex-1 place-items-center p-8 text-center text-sm text-slate-500">Pilih transaksi untuk melihat detail.</div>@endif</aside></div>
@endsection
