@extends('layouts.admin')
@section('title', 'Booking')
@section('content')
<div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-3xl font-extrabold sm:text-4xl">Pemesanan & Booking</h1><p class="mt-2 text-sm text-slate-500">Kelola permohonan booking kamar dari calon penyewa.</p></div><form class="w-full sm:w-auto"><select name="status" class="form-select w-full sm:w-40" onchange="this.form.submit()"><option value="">Semua Status</option><option value="pending" @selected(request('status') === 'pending')>Pending</option><option value="approved" @selected(request('status') === 'approved')>Approved</option><option value="rejected" @selected(request('status') === 'rejected')>Rejected</option></select></form></div>
<section class="panel overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[950px]"><thead><tr><th class="table-heading">ID Booking</th><th class="table-heading">Nama User</th><th class="table-heading">Kost & Kamar</th><th class="table-heading">Tanggal Booking</th><th class="table-heading">Status</th><th class="table-heading text-right">Aksi</th></tr></thead><tbody>
@forelse($bookings as $booking)<tr><td class="table-cell font-mono text-slate-500">#{{ $booking->booking_code }}</td><td class="table-cell"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-blue-100 text-xs font-bold text-[#12347f]">{{ Str::upper(Str::substr($booking->user->name, 0, 2)) }}</span><div><p class="font-semibold text-slate-900">{{ $booking->user->name }}</p><p class="text-xs text-slate-500">{{ $booking->user->email }}</p></div></div></td><td class="table-cell"><p class="font-semibold text-[#12347f]">{{ $booking->room->kost->name }}</p><p class="text-xs">Lantai {{ $booking->room->floor ?: '-' }} · Kamar {{ $booking->room->room_number }}</p></td><td class="table-cell"><p>{{ $booking->booking_date->format('d M Y') }}</p><p class="text-xs text-slate-500">Masuk: {{ $booking->check_in_date->format('d M Y') }}</p></td><td class="table-cell"><span @class(['rounded-full px-3 py-1 text-xs font-bold', 'bg-amber-100 text-amber-700' => $booking->status->value === 'pending', 'bg-emerald-100 text-emerald-700' => $booking->status->value === 'approved', 'bg-red-100 text-red-700' => $booking->status->value === 'rejected'])>● {{ ucfirst($booking->status->value) }}</span></td><td class="table-cell"><div class="flex justify-end gap-1"><a href="{{ route('bookings.show', $booking) }}" class="rounded p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-800"><x-icon name="eye"/></a>@if($booking->status->value === 'pending')<form method="POST" action="{{ route('bookings.approve', $booking) }}" data-confirm="Setujui booking ini?">@csrf @method('PATCH')<button title="Approve" class="rounded p-2 text-emerald-600 hover:bg-emerald-50"><x-icon name="check"/></button></form><form method="POST" action="{{ route('bookings.reject', $booking) }}" data-confirm="Tolak booking ini?">@csrf @method('PATCH')<button title="Reject" class="rounded p-2 text-red-600 hover:bg-red-50"><x-icon name="x"/></button></form>@endif</div></td></tr>
@empty<tr><td colspan="6" class="py-16 text-center text-sm text-slate-500">Belum ada booking.</td></tr>@endforelse
</tbody></table></div><div class="p-6">{{ $bookings->links() }}</div></section>
@endsection
