@extends('layouts.admin')
@section('title', 'Data Kost')
@section('content')
<div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 class="text-3xl font-extrabold tracking-tight sm:text-4xl">Data Kost</h1><p class="mt-2 text-sm text-slate-500">Manage and monitor all your property listings in one place.</p></div><a href="{{ route('kosts.create') }}" class="btn-primary w-full sm:w-auto"><x-icon name="plus"/> Tambah Kost</a></div>
<div class="panel overflow-hidden p-4 sm:p-6"><div class="mb-5 md:hidden"><form><input class="form-input" name="search" value="{{ request('search') }}" placeholder="Cari kost..."></form></div><div class="overflow-x-auto"><table class="w-full min-w-[800px]"><thead><tr><th class="table-heading">Foto</th><th class="table-heading">Nama Kost</th><th class="table-heading">Lokasi</th><th class="table-heading">Jumlah Kamar</th><th class="table-heading">Status</th><th class="table-heading text-right">Actions</th></tr></thead><tbody>
@forelse($kosts as $kost)<tr><td class="table-cell"><div class="h-12 w-14 overflow-hidden rounded-lg bg-blue-100">@if($kost->image)<img class="h-full w-full object-cover" src="{{ Storage::url($kost->image) }}" alt="">@else<div class="grid h-full place-items-center text-[#12347f]"><x-icon name="building"/></div>@endif</div></td><td class="table-cell"><p class="font-bold text-slate-900">{{ $kost->name }}</p><p class="text-xs text-slate-500">ID: {{ $kost->code }}</p></td><td class="table-cell">{{ $kost->city ?: Str::limit($kost->address, 30) }}</td><td class="table-cell">{{ $kost->rooms_count }} Kamar</td><td class="table-cell"><span @class(['rounded-full px-3 py-1 text-xs font-semibold', 'bg-emerald-100 text-emerald-700' => $kost->status->value === 'active', 'bg-slate-100 text-slate-600' => $kost->status->value !== 'active'])>{{ $kost->status->value === 'active' ? 'Aktif' : 'Non-aktif' }}</span></td><td class="table-cell"><div class="flex justify-end gap-2"><a title="Detail" href="{{ route('kosts.show', $kost) }}" class="rounded-lg p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-800"><x-icon name="eye"/></a><a title="Edit" href="{{ route('kosts.edit', $kost) }}" class="rounded-lg p-2 text-slate-500 hover:bg-blue-50 hover:text-blue-800"><x-icon name="edit"/></a><form method="POST" action="{{ route('kosts.destroy', $kost) }}" data-confirm="Hapus data kost ini?">@csrf @method('DELETE')<button class="rounded-lg p-2 text-slate-500 hover:bg-red-50 hover:text-red-600"><x-icon name="trash"/></button></form></div></td></tr>
@empty<tr><td colspan="6" class="py-16 text-center text-sm text-slate-500">Data kost belum tersedia.</td></tr>@endforelse
</tbody></table></div><div class="mt-6">{{ $kosts->links() }}</div></div>
@endsection
