@extends('layouts.admin')
@section('title', 'Data Kamar')
@section('content')
<div class="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 class="text-3xl font-extrabold sm:text-4xl">Data Kamar</h1><p class="mt-2 text-sm text-slate-500">Kelola status dan informasi seluruh kamar kos.</p></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><form><select name="status" class="form-select w-full" onchange="this.form.submit()"><option value="">Semua Status</option><option value="available" @selected(request('status') === 'available')>Tersedia</option><option value="occupied" @selected(request('status') === 'occupied')>Terisi</option></select></form><a href="{{ route('rooms.create') }}" class="btn-primary w-full"><x-icon name="plus"/> Tambah Kamar</a></div></div>
<div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
@forelse($rooms as $room)<article class="panel flex min-h-72 flex-col p-6"><div class="flex items-start justify-between"><div><h2 class="text-xl font-extrabold">{{ $room->room_number }}</h2><p class="mt-1 text-sm text-slate-600">{{ $room->kost->name }}</p>@if($room->floor)<p class="text-xs text-slate-400">Lantai {{ $room->floor }}</p>@endif</div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $room->status->value === 'available' ? 'bg-emerald-300 text-emerald-800' : 'bg-red-100 text-red-700' }}">● {{ $room->status->value === 'available' ? 'Tersedia' : 'Terisi' }}</span></div><p class="mt-6 text-xl font-extrabold text-[#12347f]">Rp {{ number_format($room->price, 0, ',', '.') }}<span class="text-sm font-normal text-slate-500">/bln</span></p><div class="my-5 h-px bg-slate-200"></div><div class="min-h-12">@if($room->currentTenant)<div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-full bg-[#244393] text-xs font-bold text-white">{{ Str::upper(Str::substr($room->currentTenant->user->name, 0, 2)) }}</span><div><p class="text-sm font-semibold">{{ $room->currentTenant->user->name }}</p><p class="text-[10px] text-slate-500">Sewa sejak {{ $room->currentTenant->check_in->format('d M Y') }}</p></div></div>@else<p class="flex items-center gap-2 text-sm text-slate-400"><x-icon name="users"/> Kosong</p>@endif</div><div class="mt-auto flex justify-end gap-2 pt-4"><a href="{{ route('rooms.edit', $room) }}" class="rounded p-2 text-slate-600 hover:bg-blue-50 hover:text-blue-800"><x-icon name="edit"/></a><form method="POST" action="{{ route('rooms.destroy', $room) }}" data-confirm="Hapus kamar ini?">@csrf @method('DELETE')<button class="rounded p-2 text-slate-600 hover:bg-red-50 hover:text-red-600"><x-icon name="trash"/></button></form></div></article>
@empty<div class="panel col-span-full py-20 text-center text-sm text-slate-500">Belum ada data kamar.</div>@endforelse
</div><div class="mt-7">{{ $rooms->links() }}</div>
@endsection
